"""
Visualization utilities for Vanishing / Exploding Gradient experiments.

The functions in this module compare experiment histories generated by:

    NeuralNetwork.fit()

Expected history structure:

    history = {
        "epoch": ...,
        "train_loss": ...,
        "val_loss": ...,
        "train_acc": ...,
        "val_acc": ...,

        "dW_norm": ...,
        "dW_rms": ...,
        "dZ_norm": ...,
        "dZ_rms": ...,
    }

Layer-wise gradient metrics have shape:

    (n_epochs, n_layers)

For example, with:

    50 epochs
    20 weighted layers

the shape is:

    (50, 20)
"""

from collections.abc import Mapping
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

# ============================================================
# CONSTANTS
# ============================================================

EPS = 1e-12


SUPPORTED_ARRAY_KEYS = (
    "epoch",
    "loss",  # Legacy alias for train_loss
    "train_loss",
    "val_loss",
    "train_acc",
    "val_acc",
    "dW_norm",
    "dW_rms",
    "dZ_norm",
    "dZ_rms",
)


# ============================================================
# SAVE / LOAD HISTORY
# ============================================================


def save_history(history, path):
    """
    Save experiment history to an .npz file.

    Parameters
    ----------
    history : Mapping
        History returned by NeuralNetwork.fit().

    path : str | pathlib.Path
        Output path.

    Example
    -------
    save_history(
        baseline_history,
        "results/histories/baseline.npz",
    )
    """
    validate_history(history)

    path = Path(path)

    # Automatically create parent directory.
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    arrays = {
        key: np.asarray(history[key])
        for key in SUPPORTED_ARRAY_KEYS
        if key in history
    }

    np.savez(
        path,
        **arrays,
    )


def load_history(path):
    """
    Load experiment history from an .npz file.

    Parameters
    ----------
    path : str | pathlib.Path

    Returns
    -------
    dict
        Loaded experiment history.
    """
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"History file does not exist: {path}")

    with np.load(
        path,
        allow_pickle=False,
    ) as file:

        history = {key: file[key] for key in file.files}

    validate_history(history)

    return history


# ============================================================
# SAVE FIGURE
# ============================================================


def save_figure(
    fig,
    path,
    dpi=150,
    bbox_inches="tight",
):
    """
    Save a Matplotlib figure.

    Parent directories are created automatically.

    Example
    -------
    fig, _ = plot_experiment_summary(histories)

    save_figure(
        fig,
        "results/figures/summary.png",
    )
    """
    path = Path(path)

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig.savefig(
        path,
        dpi=dpi,
        bbox_inches=bbox_inches,
    )


# ============================================================
# HISTORY VALIDATION
# ============================================================


def validate_history(
    history,
    required_keys=(),
):
    """
    Validate an experiment history.

    Parameters
    ----------
    history : Mapping

    required_keys : iterable[str]
        Additional keys required by a specific plot.
    """
    if not isinstance(
        history,
        Mapping,
    ):
        raise TypeError(
            "history must be a mapping " "of metric names to arrays."
        )

    # --------------------------------------------------------
    # Epoch
    # --------------------------------------------------------
    if "epoch" not in history:
        raise KeyError("history is missing required key 'epoch'.")

    missing = [key for key in required_keys if key not in history]

    if missing:
        raise KeyError(f"history is missing required keys: {missing}")

    epochs = np.asarray(history["epoch"])

    if epochs.ndim != 1:
        raise ValueError("history['epoch'] must be a 1-D array.")

    if epochs.size == 0:
        raise ValueError("history['epoch'] cannot be empty.")

    if not np.issubdtype(
        epochs.dtype,
        np.number,
    ):
        raise TypeError("history['epoch'] must contain numeric values.")

    if not np.all(np.isfinite(epochs)):
        raise ValueError("history['epoch'] contains NaN or infinity.")

    if epochs.size > 1 and np.any(np.diff(epochs) <= 0):
        raise ValueError("history['epoch'] must be strictly increasing.")

    # --------------------------------------------------------
    # Required metrics
    # --------------------------------------------------------
    for key in required_keys:

        values = np.asarray(history[key])

        if values.ndim == 0:
            raise ValueError(f"history['{key}'] must contain an array.")

        if values.shape[0] != epochs.size:
            raise ValueError(
                f"history['{key}'] has "
                f"{values.shape[0]} records, "
                f"but history['epoch'] has "
                f"{epochs.size}."
            )

        if not np.issubdtype(
            values.dtype,
            np.number,
        ):
            raise TypeError(
                f"history['{key}'] must contain " f"numeric values."
            )

        if not np.all(np.isfinite(values)):
            raise ValueError(f"history['{key}'] contains " f"NaN or infinity.")


# ============================================================
# VALIDATE MULTIPLE EXPERIMENTS
# ============================================================


def _validate_histories(histories):
    """
    Validate mapping:

        {
            "Experiment A": history_a,
            "Experiment B": history_b,
        }
    """
    if not isinstance(
        histories,
        Mapping,
    ):
        raise TypeError("histories must be a mapping.")

    if not histories:
        raise ValueError("histories cannot be empty.")

    for name, history in histories.items():

        if not isinstance(name, str):
            raise TypeError("Experiment names must be strings.")

        if not name.strip():
            raise ValueError("Experiment names cannot be empty.")

        try:
            validate_history(history)

        except (
            TypeError,
            ValueError,
            KeyError,
        ) as error:

            raise type(error)(
                f"Invalid history for experiment " f"'{name}': {error}"
            ) from error


# ============================================================
# INTERNAL METRIC HELPERS
# ============================================================


def _layer_metric(
    history,
    key,
):
    """
    Return a layer-wise metric.

    Expected shape:

        (n_epochs, n_layers)
    """
    validate_history(
        history,
        required_keys=(key,),
    )

    data = np.asarray(
        history[key],
        dtype=float,
    )

    if data.ndim != 2:
        raise ValueError(
            f"history['{key}'] must have shape " f"(n_epochs, n_layers)."
        )

    if data.shape[1] == 0:
        raise ValueError(f"history['{key}'] contains zero layers.")

    if np.any(data < 0):
        raise ValueError(
            f"history['{key}'] must contain "
            f"non-negative gradient magnitudes."
        )

    return data


def _scalar_metric(
    history,
    key,
    *,
    nonnegative=False,
):
    """
    Return a scalar metric recorded once per epoch.

    Expected shape:

        (n_epochs,)
    """
    validate_history(
        history,
        required_keys=(key,),
    )

    values = np.asarray(
        history[key],
        dtype=float,
    )

    if values.ndim != 1:
        raise ValueError(f"history['{key}'] must be a 1-D array.")

    if nonnegative and np.any(values < 0):
        raise ValueError(
            f"history['{key}'] must contain " f"non-negative values."
        )

    return values


def _metric_key(
    history,
    metric,
    split,
):
    """
    Resolve train / validation metric names.

    Examples:

        metric="loss", split="train"
            -> train_loss

        metric="acc", split="val"
            -> val_acc
    """
    if split not in {
        "train",
        "val",
    }:
        raise ValueError("split must be either 'train' or 'val'.")

    key = f"{split}_{metric}"

    # Compatibility with older history structure.
    if (
        metric == "loss"
        and split == "train"
        and key not in history
        and "loss" in history
    ):
        key = "loss"

    return key


def _get_ax(
    ax,
    figsize=(7, 4.5),
):
    """
    Create a Matplotlib axis if one was not provided.
    """
    if ax is None:

        fig, ax = plt.subplots(figsize=figsize)

    else:
        fig = ax.figure

    return fig, ax


def _record_index(
    epochs,
    epoch,
):
    """
    Resolve a requested epoch.

    epoch=None or epoch=-1:
        select final recorded epoch.

    numeric epoch:
        select the nearest recorded epoch.
    """
    if epoch is None or epoch == -1:
        return len(epochs) - 1

    if not np.isscalar(epoch):
        raise TypeError("epoch must be a scalar number, " "-1, or None.")

    if not np.isfinite(epoch):
        raise ValueError("epoch must be finite.")

    return int(np.argmin(np.abs(epochs - epoch)))


# ============================================================
# GRADIENT METRICS
# ============================================================


def gradient_ratio(
    history,
    key="dW_rms",
):
    """
    Calculate gradient ratio:

        first layer gradient
        --------------------
         last layer gradient

    for every recorded epoch.

    A very small value can indicate that gradients reaching
    the earliest layer are much smaller than gradients near
    the output layer.

    Parameters
    ----------
    history : Mapping

    key : str
        Usually:
            dW_rms
            dZ_rms
    """
    data = _layer_metric(
        history,
        key,
    )

    first_layer = data[:, 0]
    last_layer = data[:, -1]

    return first_layer / np.maximum(
        last_layer,
        EPS,
    )


# ============================================================
# PLOT: GRADIENT BY LAYER
# ============================================================


def plot_grad_by_layer(
    histories,
    epoch=-1,
    key="dW_rms",
    ax=None,
):
    """
    Compare gradient magnitude across network layers.

    Parameters
    ----------
    histories : Mapping[str, history]

    epoch : int | float | None
        -1 / None:
            use last epoch.

        number:
            use nearest recorded epoch.

    key : str
        Gradient metric.

        Recommended:
            dW_rms
            dZ_rms
    """
    _validate_histories(histories)

    fig, ax = _get_ax(ax)

    for name, history in histories.items():

        epochs = np.asarray(
            history["epoch"],
            dtype=float,
        )

        data = _layer_metric(
            history,
            key,
        )

        index = _record_index(
            epochs,
            epoch,
        )

        layers = np.arange(
            1,
            data.shape[1] + 1,
        )

        values = np.maximum(
            data[index],
            EPS,
        )

        ax.plot(
            layers,
            values,
            marker="o",
            markersize=4,
            label=(f"{name} " f"(epoch {epochs[index]:g})"),
        )

    ax.set_yscale("log")

    ax.set_xlabel("Layer")

    ax.set_ylabel(key)

    ax.set_title(f"Gradient by Layer ({key})")

    ax.legend()

    ax.grid(
        True,
        which="both",
        alpha=0.25,
    )

    return fig, ax


# ============================================================
# PLOT: GRADIENT OVER EPOCHS
# ============================================================


def plot_grad_over_epochs(
    histories,
    layer=1,
    key="dW_rms",
    metric="layer",
    ax=None,
):
    """
    Compare gradient evolution during training.

    Parameters
    ----------
    metric : str

        "layer"
            Plot gradient of one selected layer.

        "ratio"
            Plot:

                gradient(layer 1)
                -----------------
                gradient(last layer)
    """
    _validate_histories(histories)

    if metric not in {
        "layer",
        "ratio",
    }:
        raise ValueError("metric must be either " "'layer' or 'ratio'.")

    if not isinstance(
        layer,
        (int, np.integer),
    ):
        raise TypeError("layer must be an integer.")

    fig, ax = _get_ax(ax)

    for name, history in histories.items():

        epochs = np.asarray(
            history["epoch"],
            dtype=float,
        )

        data = _layer_metric(
            history,
            key,
        )

        # ------------------------------------------------------
        # Gradient ratio
        # ------------------------------------------------------
        if metric == "ratio":

            values = gradient_ratio(
                history,
                key,
            )

        # ------------------------------------------------------
        # One specific layer
        # ------------------------------------------------------
        else:

            if layer < 1 or layer > data.shape[1]:
                raise ValueError(
                    f"layer {layer} is invalid "
                    f"for experiment '{name}'. "
                    f"Expected 1..{data.shape[1]}."
                )

            values = data[
                :,
                layer - 1,
            ]

        ax.plot(
            epochs,
            np.maximum(
                values,
                EPS,
            ),
            label=name,
        )

    ax.set_yscale("log")

    if metric == "ratio":

        ax.axhline(
            1.0,
            linestyle="--",
            linewidth=1,
        )

        ax.set_ylabel(f"{key}: Layer 1 / Last Layer")

        ax.set_title("Gradient Ratio over Epochs")

    else:

        ax.set_ylabel(key)

        ax.set_title(f"Gradient at Layer {layer} " f"over Epochs")

    ax.set_xlabel("Epoch")

    ax.legend()

    ax.grid(
        True,
        which="both",
        alpha=0.25,
    )

    return fig, ax


# ============================================================
# PLOT: LOSS
# ============================================================


def plot_loss_over_epochs(
    histories,
    split="val",
    ax=None,
):
    """
    Compare training or validation loss.

    split:
        "train"
        "val"
    """
    _validate_histories(histories)

    fig, ax = _get_ax(ax)

    for name, history in histories.items():

        key = _metric_key(
            history,
            "loss",
            split,
        )

        epochs = np.asarray(
            history["epoch"],
            dtype=float,
        )

        values = _scalar_metric(
            history,
            key,
            nonnegative=True,
        )

        ax.plot(
            epochs,
            values,
            label=name,
        )

    ax.set_xlabel("Epoch")

    ax.set_ylabel(f"{split.capitalize()} Loss")

    ax.set_title(f"{split.capitalize()} Loss over Epochs")

    ax.legend()

    ax.grid(
        True,
        alpha=0.25,
    )

    return fig, ax


# ============================================================
# PLOT: ACCURACY
# ============================================================


def plot_acc_over_epochs(
    histories,
    split="val",
    ax=None,
):
    """
    Compare training or validation accuracy.
    """
    _validate_histories(histories)

    fig, ax = _get_ax(ax)

    for name, history in histories.items():

        key = _metric_key(
            history,
            "acc",
            split,
        )

        epochs = np.asarray(
            history["epoch"],
            dtype=float,
        )

        values = _scalar_metric(
            history,
            key,
        )

        if np.any((values < 0) | (values > 1)):
            raise ValueError(
                f"history['{key}'] for experiment "
                f"'{name}' must contain values "
                f"between 0 and 1."
            )

        ax.plot(
            epochs,
            values,
            label=name,
        )

    ax.set_xlabel("Epoch")

    ax.set_ylabel(f"{split.capitalize()} Accuracy")

    ax.set_title(f"{split.capitalize()} Accuracy " f"over Epochs")

    ax.set_ylim(
        0,
        1,
    )

    ax.legend()

    ax.grid(
        True,
        alpha=0.25,
    )

    return fig, ax


# ============================================================
# COMPLETE EXPERIMENT DASHBOARD
# ============================================================


def plot_experiment_summary(
    histories,
    epoch=-1,
    layer=1,
    key="dW_rms",
    split="val",
):
    """
    Create a 2 x 2 experiment dashboard.

    Layout:

        ┌──────────────────────┬──────────────────────┐
        │ Gradient by Layer    │ Gradient Ratio       │
        │                      │ over Epochs          │
        ├──────────────────────┼──────────────────────┤
        │ Loss over Epochs     │ Accuracy over Epochs │
        └──────────────────────┴──────────────────────┘
    """

    _validate_histories(histories)

    fig, axes = plt.subplots(
        2,
        2,
        figsize=(14, 9),
    )

    # --------------------------------------------------------
    # Top-left
    # Gradient magnitude across layers
    # --------------------------------------------------------
    plot_grad_by_layer(
        histories,
        epoch=epoch,
        key=key,
        ax=axes[0, 0],
    )

    # --------------------------------------------------------
    # Top-right
    # Gradient propagation ratio during training
    # --------------------------------------------------------
    plot_grad_over_epochs(
        histories,
        layer=layer,
        key=key,
        metric="ratio",
        ax=axes[0, 1],
    )

    # --------------------------------------------------------
    # Bottom-left
    # Loss
    # --------------------------------------------------------
    plot_loss_over_epochs(
        histories,
        split=split,
        ax=axes[1, 0],
    )

    # --------------------------------------------------------
    # Bottom-right
    # Accuracy
    # --------------------------------------------------------
    plot_acc_over_epochs(
        histories,
        split=split,
        ax=axes[1, 1],
    )

    fig.suptitle(
        "Vanishing / Exploding Gradient " "Experiment Comparison",
        fontsize=14,
    )

    fig.tight_layout(rect=(0, 0, 1, 0.97))

    return fig, axes
